name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/format.yml@53c85fabe6ac4ed7a96e49a005f03fa6cc63d2ac # main
    with:
      command: "format"
    secrets: inherit
